AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Go com OpenTelemetry

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: helloworld/
      Handler: bootstrap  # Handler padrão para Go (arquivo binário)
      Runtime: provided.al2  # Lambda com runtime customizado (Go)
      Architectures:
        - arm64
      Environment:
        Variables:
          OTEL_SERVICE_NAME: lambda-go
      Tracing: Active  # Ativa X-Ray (opcional, se quiser combinar com OTel)

Globals:
  Function:
    Timeout: 10