service: aws-golang

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: provided.al2
  architecture: x86_64
  region: us-east-1
  stage: ${opt:stage,'dev'}
  memorySize: 256
  timeout: 10
  layers:
    - arn:aws:lambda:us-east-1:233054480867:layer:otel-collector:1 # https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/README.md#build-your-opentelemetry-collector-lambda-layer-from-scratch
  tracing:
    lambda: true
    apiGateway: true

functions:
  HelloWorldFunction:
    handler: main
    events:
      - httpApi:
          path: /hello
          method: get

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  serverless-offline:
    useDocker: true
    lambdaRuntime: provided.al2
    dockerImage: public.ecr.aws/lambda/go:1
    dockerHost: host.docker.internal
    dockerNetwork: bridge
    noTimeout: true
    showOutput: true
    printOutput: true
    httpPort: 3000