service: aws-golang

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: provided.al2
  architecture: x86_64
  region: us-east-1
  stage: ${opt:stage,'dev'}
  memorySize: 256
  timeout: 10

functions:
  HelloWorldFunction:
    handler: main # Changed from ./aws-golang/main.go or bin/main
    events:
      - httpApi:
          path: /hello
          method: get

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  serverless-offline:
    useDocker: true
    lambdaRuntime: provided.al2
    dockerImage: public.ecr.aws/lambda/go:1
    dockerHost: host.docker.internal
    dockerNetwork: host
    showOutput: true
    printOutput: true